export const GET_MESSAGEBY_TEACHER_REQUEST = "GET_MESSAGEBY_TEACHER_REQUEST";
export const GET_MESSAGEBY_TEACHER_SUCCESS = "GET_MESSAGEBY_TEACHER_SUCCESS";
export const GET_MESSAGEBY_TEACHER_FAILURE = "GET_MESSAGEBY_TEACHER_FAILURE";