export const GET_STUDENT_BY_CLASSID_REQUEST = "GET_STUDENT_BY_CLASSID_REQUEST";
export const GET_STUDENT_BY_CLASSID_SUCCESS = "GET_STUDENT_BY_CLASSID_SUCCESS";
export const GET_STUDENT_BY_CLASSID_FAILURE = "GET_STUDENT_BY_CLASSID_FAILURE";