export const GET_SUBJECTS_BY_TEACHERID_REQUEST = "GET_SUBJECTS_BY_TEACHERID_REQUEST";
export const GET_SUBJECTS_BY_TEACHERID_SUCCESS = "GET_SUBJECTS_BY_TEACHERID_SUCCESS";
export const GET_SUBJECTS_BY_TEACHERID_FAILURE = "GET_SUBJECTS_BY_TEACHERID_FAILURE";