export const SENT_MESSAGE_TO_PARENT_REQUEST = "SENT_MESSAGE_TO_PARENT_REQUEST";
export const SENT_MESSAGE_TO_PARENT_SUCCESS = "SENT_MESSAGE_TO_PARENT_SUCCESS";
export const SENT_MESSAGE_TO_PARENT_FAILURE = "SENT_MESSAGE_TO_PARENT_FAILURE";